
version: '3.9'

services:
  pythonapp:
    container_name: python
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres_user:123@db:5432/db
      - SECRET_KEY=532f7ffa0a70512660d0bc83ad3388c1
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgres/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}